# Generated by Django 3.2.5 on 2021-07-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_emprestimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="dataem",
            field=models.CharField(max_length=100),
        ),
    ]
