# Generated by Django 3.2.5 on 2021-08-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210726_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='estado',
            field=models.CharField(choices=[(1, 'Emprestado'), (2, 'Devolvido')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
