# Generated by Django 3.2.5 on 2021-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_emprestimo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='estado',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('fazendo', 'Devolvido')], max_length=10),
        ),
    ]
