# Generated by Django 3.2.5 on 2021-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_emprestimo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='estado',
            field=models.CharField(choices=[('emprestado', 'emprestado'), ('devolvido', 'devolvido')], max_length=10),
        ),
    ]
