# Generated by Django 3.2.5 on 2021-08-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_emprestimo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='serie',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
